org: timbudweg
app: driveinmarkt-app
service: driveinMarkt
nextApp:
  component: "serverless-next.js"

functions:
  createUser:
    handler: backend/signup.signup
    events:
      - http:
          method: post
          cors: true
          path: /createUser


provider:
  name: aws
  runtime: nodejs12.x
  region: "eu-central-1"
  environment:
    DYNAMODB_TABLE: users