Resources:
  CognitoUserPoolCognitoUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: ${self:service}_${self:provider.stage}_user_pool
      UsernameAttributes:
        - email
      AutoVerifiedAttributes:
        - email

  CognitoUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: ${self:service}_${self:provider.stage}_client
      UserPoolId:
        Ref: CognitoUserPoolCognitoUserPool
      GenerateSecret: false
